// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xywpotmfypaawmiesbty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5d3BvdG1meXBhYXdtaWVzYnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODY0NzIsImV4cCI6MjA2MjI2MjQ3Mn0.engfiL8AsrgzAWMjuSASe5-UPJRIRJr6VE_1jlrfrxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);